-- local capabilities = vim.lsp.protocol.make_client_capabilities()
local blink_cmp = require("blink.cmp")
local capabilities = blink_cmp.get_lsp_capabilities({ include_nvim_defaults = true })
capabilities.textDocument.colorProvider = {
	dynamicRegistration = true,
}
capabilities.textDocument.completion.completionItem.snippetSupport = true

return {
	cmd = { "tailwindcss-language-server", "--stdio" },
	settings = {
		capabilities = capabilities,
		tailwindcss = {
			experimental = {
				classRegex = {
					{ "cva\\(([^)]*)\\)", "[\"'`]([^\"'`]*).*?[\"'`]" },
					{ "cx\\(([^)]*)\\)", "(?:'|\"|`)([^']*)(?:'|\"|`)" },
					-- ":\\s*['\"`]([^'\"`]*)['\"`]", -- This regex will match CSS variables
					-- { "class\\s*=\\s*['\"]([^'\"]*)['\"]", "[\"']([^\"']*)[\"']" },
					-- { "className\\s*=\\s*['\"]([^'\"]*)['\"]", "[\"']([^\"']*)[\"']" },
				},
			},
			validate = true,
			colorDecorators = true,
			lint = {
				cssConflict = "warning",
				invalidApply = "error",
				invalidScreen = "error",
				invalidVariant = "error",
				invalidConfigPath = "error",
				invalidTailwindDirective = "error",
				recommendedVariantOrder = "warning",
			},
			classAttributes = {
				"class",
				"className",
				"class:list",
				"classList",
				"ngClass",
			},
			includeLanguages = {
				eelixir = "html-eex",
				eruby = "erb",
				templ = "html",
				htmlangular = "html",
			},
		},
	},
	filetypes = {
		"aspnetcorerazor",
		"astro",
		"astro-markdown",
		"blade",
		"clojure",
		"django-html",
		"htmldjango",
		"edge",
		"eelixir",
		"elixir",
		"ejs",
		"erb",
		"eruby",
		"gohtml",
		"gohtmltmpl",
		"haml",
		"handlebars",
		"hbs",
		"html",
		"htmlangular",
		"html-eex",
		"heex",
		"jade",
		"leaf",
		"liquid",
		"markdown",
		"mdx",
		"mustache",
		"njk",
		"nunjucks",
		"php",
		"razor",
		"slim",
		"twig",
		"css",
		"less",
		"postcss",
		"sass",
		"scss",
		"stylus",
		"sugarss",
		"javascript",
		"javascriptreact",
		"reason",
		"rescript",
		"typescript",
		"typescriptreact",
		"vue",
		"svelte",
		"templ",
	},
	root_markers = {
		"tailwind.config.js",
		"tailwind.config.ts",
		"postcss.config.js",
		"postcss.config.ts",
		"package.json",
		"node_modules",
		".git",
	},
}
